version: '2'

services:

  app:
    # Build image using the folowing Dockerfile:
    build: 
      context: .
      dockerfile: Dockerfile
    # Name of the image to be built:
    image: ImageName
  
  # USAGE: docker-compose -f docker-compose-test-local-predeployment.yml run --rm unitTests
  unitTests:
    # get image from docker respiratory:
    image: mhart/alpine-node:latest
    # Where does it mount !>?
    volumes:
      # Volume attached to the host through docker-machine VM.
      - .:/app
    working_dir: /app/nodeServer
    # Download dependencies & run tests. 
    # use /bin/sh where bash is not installed (i.e. alpine-node image).
    command: /bin/sh -c "npm install && npm run test"

