version: "2.1"

# USAGE (cd to project root): docker-compose -f ./setup/<docker-compose>.yml up 
services:

  nodejs:
    build:
      # Context of docker file that will be executed.
      context: ../../
      dockerfile: ./setup/container/nodejsServer.dockerfile
    image: myuserindocker/radioscanner-webapp-nodejs:latest
    command: nodemon --debug=5858
    # Relative to this file path, not the dockerfile context.
    volumes:
      - ../../source/:/app/source/
    ports:
      - "8084:80"
    links:
      - "apachestreamproxy:apachestreamproxy"
  
  apachestreamproxy:
    build:
      context: ../../
      dockerfile: ./setup/container/apacheStreamServer.dockerfile
    image: myuserindocker/radioscanner-webapp-apachestreamproxy:latest
    # network_mode: "host"
    # ports:
    #   - "8085:80"
